### ISSUE TITLE
docker-compose setup

### ISSUE THREAD

**Issue by Anmirazik** [citrineos/citrineos-core#13]
```
> @citrineos/server@1.0.0 start-unix:docker
> export APP_ENV=docker && npx nodemon

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,js
[nodemon] starting `npx ts-node ./src/index.ts`
2023-10-29 19:54:41.496 INFO    /node_modules/@citrineos/provisioning/lib/module/module.js:96   CitrineOS Logger:ProvisioningModule     Initializing...
Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
    at module.exports.runLoopOnce (/usr/server/node_modules/deasync/index.js:65:10)
    at module.exports (/usr/server/node_modules/deasync-promise/index.js:13:9)
    at new ProvisioningModule (/usr/server/node_modules/@citrineos/provisioning/lib/module/module.js:97:44)
    at new CitrineOSServer (/usr/server/src/index.ts:84:36)
    at Object.<anonymous> (/usr/server/src/index.ts:155:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/usr/server/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/server/node_modules/ts-node/src/index.ts:1621:12) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal'
}
[nodemon] app crashed - waiting for file changes before starting...
```

I face this error when run `docker-compose up -d `in the `50_Server ` file . This errors comes from the citrine docker container which leads to the port 8081 unreachable from the browser

**Comment by joll90** [comment]
Unfortunately `v0.0.1` encounters a problem running locally on docker on Ubuntu operating systems. The fix for this problem is described below:

1. Go to the folder 50_Server/src/config/envs where you can find a file called `docker.ts`
2. In this file replace all occurrences of `host.docker.internal` with `172.18.0.1` 
3. Save the file and go back into `50_Server` and run `docker-compose up -d`
4. CitrineOS now loads without a problem

**Comment by scarter93** [comment]
It sounds like upgrading the docker engine will also work: 
```
Starting from version 20.10 , the Docker Engine now also supports communicating with the Docker host via host.docker.internal on Linux.
Unfortunately, this won't work out of the box on Linux because you need to add the extra — add-hostrun flag:

--add-host=host.docker.internal:host-gateway
```

For docker compose we can use the following. Will need to confirm if this impacts other Operating Systems.

```
extra_hosts:
      -"host.docker.internal:host-gateway"
```

Finally, We can also probably use docker compose .env files to make it a bit cleaner before running, providing a template & documentation.

**Comment by scarter93** [comment]
@Anmirazik I created a branch `13-docker-compose-setup` with the above change to Docker Compose. Can you see if this resolves your issue? 

Thanks!

**Comment by Anmirazik** [comment]
> @Anmirazik I created a branch `13-docker-compose-setup` with the above change to Docker Compose. Can you see if this resolves your issue?
> 
> Thanks!

yes it works ! Thank you very much

**Comment by scarter93** [comment]
Great @Anmirazik we decided to go the route of docker service discovery instead, but that should also work for you :)
