### ISSUE TITLE
Runnig docker compose fails to start citrine service

### ISSUE THREAD

**Issue by couryrr-afs** [citrineos/citrineos-core#17]
I ran through the setup for the project. When I run the `docker compose up -d` command it looks like everything ran fine. Even checking via Docker Desktop all of the services are green. I was having issues getting a connection and dug into it. I found that the citrine service was started but stuck in an error state. 

I can kill the service and run the local version just fine.

```
2023-11-09 13:50:50 /usr/server/node_modules/bindings/bindings.js:126
2023-11-09 13:50:50   err = new Error(
2023-11-09 13:50:50         ^
2023-11-09 13:50:50 Error: Could not locate the bindings file. Tried:
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/build/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/build/Debug/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/build/Release/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/out/Debug/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/Debug/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/out/Release/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/Release/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/build/default/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/compiled/18.18.2/linux/arm64/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/addon-build/release/install-root/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/addon-build/debug/install-root/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/addon-build/default/install-root/deasync.node
2023-11-09 13:50:50  → /usr/server/node_modules/deasync/lib/binding/node-v108-linux-arm64/deasync.node
2023-11-09 13:50:50     at bindings (/usr/server/node_modules/bindings/bindings.js:126:9)
2023-11-09 13:50:50     at Object.<anonymous> (/usr/server/node_modules/deasync/index.js:30:31)
2023-11-09 13:50:50     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-11-09 13:50:50     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-11-09 13:50:50     at Object.require.extensions.<computed> [as .js] (/usr/server/node_modules/ts-node/src/index.ts:1608:43)
2023-11-09 13:50:50     at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-11-09 13:50:50     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
2023-11-09 13:50:50     at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-11-09 13:50:50     at require (node:internal/modules/cjs/helpers:119:18)
2023-11-09 13:50:50     at Object.<anonymous> (/usr/server/node_modules/deasync-promise/index.js:1:12) {
2023-11-09 13:50:50   tries: [
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/build/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/build/Debug/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/build/Release/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/out/Debug/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/Debug/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/out/Release/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/Release/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/build/default/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/compiled/18.18.2/linux/arm64/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/addon-build/release/install-root/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/addon-build/debug/install-root/deasync.node',
2023-11-09 13:50:50 [nodemon] app crashed - waiting for file changes before starting...
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/addon-build/default/install-root/deasync.node',
2023-11-09 13:50:50     '/usr/server/node_modules/deasync/lib/binding/node-v108-linux-arm64/deasync.node'
2023-11-09 13:50:50   ]
2023-11-09 13:50:50 }
```

**Comment by couryrr-afs** [comment]
I wiped all existing citrineOS docker related content just to have a clean slate. Checked out the branch specified. Then ran the the steps in the README.md again.

```
cd citrineos-core
git checkout rc-0.1.1
cd 50_Server
./unix-init-install-all.sh
docker compose up -d
```

Running `docker ps -a` shows a couple of issues.

```
~/Documents/code/citrineos-core/50_Server (rc-0.1.1) » docker ps  -a                                                                                                                                                                    coury.richards@AFSMW697035304
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS                    PORTS                                                                                                         NAMES
1613a00b2e66   50_server-citrine                                                                         "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes               0.0.0.0:8080-8081->8080-8081/tcp                                                                              50_server-citrine-1
c043ffb0036b   rabbitmq:3-management                                                                     "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes (healthy)     4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   50_server-amqp-broker-1
042f6b210371   directus/directus:latest                                                                  "docker-entrypoint.s…"   18 minutes ago   Exited (1) 18 minutes ago                                                                                                                 50_server-directus-1
5843bcda5455   redis:latest                                                                              "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes (healthy)     0.0.0.0:6379->6379/tcp                                                                                        50_server-redis-1
d6fa6a18a4b1   citrineos/postgres:latest                                                                 "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes               0.0.0.0:5432->5432/tcp                                                                                        50_server-ocpp-db-1                                                                                      50_server-ocpp-db-1
```

`50_server-citrine-1` and `50_server-ocpp-db-1` are not marked healthy and `50_server-directus-1` exited (there is a dep on citrine starting that is not checked in the docker-compose.yml).

The citrine service did not start because of

```
~/Documents/code/citrineos-core/50_Server (rc-0.1.1) » docker logs 50_server-citrine-1                                                                                                                                                coury.richards@AFSMW697035304

> @citrineos/server@1.0.0 start-unix:docker
> export APP_ENV=docker && npx nodemon

npm WARN exec The following package was not found and will be installed: nodemon@3.0.1
[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,js
[nodemon] starting `npx ts-node ./src/index.ts`
npm WARN exec The following package was not found and will be installed: ts-node@10.9.1
/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts(17,61): error TS2307: Cannot find module '@citrineos/authorization' or its corresponding type declarations.
src/index.ts(18,59): error TS2307: Cannot find module '@citrineos/availability' or its corresponding type declarations.
src/index.ts(19,108): error TS2307: Cannot find module '@citrineos/base' or its corresponding type declarations.
src/index.ts(20,55): error TS2307: Cannot find module '@citrineos/monitoring' or its corresponding type declarations.
src/index.ts(21,59): error TS2307: Cannot find module '@citrineos/provisioning' or its corresponding type declarations.
src/index.ts(22,57): error TS2307: Cannot find module '@citrineos/transaction' or its corresponding type declarations.
src/index.ts(23,63): error TS2307: Cannot find module '@citrineos/util' or its corresponding type declarations.
src/index.ts(24,40): error TS2307: Cannot find module '@fastify/type-provider-json-schema-to-ts' or its corresponding type declarations.
src/index.ts(25,17): error TS2307: Cannot find module 'ajv' or its corresponding type declarations.
src/index.ts(26,42): error TS2307: Cannot find module 'fastify' or its corresponding type declarations.
src/index.ts(27,33): error TS2307: Cannot find module 'tslog' or its corresponding type declarations.
src/index.ts(79,46): error TS7031: Binding element 'schema' implicitly has an 'any' type.
src/index.ts(79,54): error TS7031: Binding element 'method' implicitly has an 'any' type.
src/index.ts(79,62): error TS7031: Binding element 'url' implicitly has an 'any' type.
src/index.ts(79,67): error TS7031: Binding element 'httpPart' implicitly has an 'any' type.
src/index.ts(108,9): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(109,9): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(110,9): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(134,13): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(143,21): error TS7006: Parameter 'address' implicitly has an 'any' type.
src/index.ts(145,22): error TS7006: Parameter 'error' implicitly has an 'any' type.
src/index.ts(147,17): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(157,5): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

    at createTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  diagnosticCodes: [
    2307, 2307, 2307, 2307,
    2307, 2307, 2307, 2307,
    2307, 2307, 2307, 7031,
    7031, 7031, 7031, 2580,
    2580, 2580, 2580, 7006,
    7006, 2580, 2580
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
```
I took a quick look through the docker changes in the branch and nothing is immediately popping out at me. I will continue to do some troubleshooting.

**Comment by thanaParis** [comment]
I was able to recreate an issue with Directus from a fresh clone, but the Citrine server started up fine for me.

Judging from the error output, you may need to run 'docker-compose down' first, then 'docker-compose build' before running 'docker-compose up'. The issue I ran into with Directus from a fresh clone appeared to be caused by docker images existing on my machine from previous builds and these commands fixed it.

In case the above doesn't help, could you share what OS/version you're using, as well as your node, npm, and tsc version? Also the logs from your Directus instance, so I can see if it's suffering the same issue I ran into.

**Comment by couryrr-afs** [comment]
I am using a MacBook Pro M2 OS is Ventura. 

```
~/Documents/code/citrineos-core/50_Server (rc-0.1.1) » npm --version 
10.1.0
-----------------------------------------------------------------------------
~/Documents/code/citrineos-core/50_Server (rc-0.1.1) » node -v 
v20.9.0
```
I do not have a global TypeScript Compiler installed globally so it should be whatever the project requires (5.0.4 based on the package.json). I do not think this is relevant any longer.

I  was able complete the steps outlined. From the folder `citrineos-core/50_Server` I did a `docker compose down` which ran successfully. I then attempt to run a `docker compose build`. There was an issue here. In the `docker-compose.yml` file the below would need to be update adding a dot to the dockerfile line.

```
citrine:
    build:
      context: ../
      dockerfile: ./50_Server/docker/Dockerfile <- added the dot
```

With that I am not seeing the issue with Directus booting. 

The issue within CitrineOS has reverted back to the original issue I was seeing. I saw some notes that this can occur if the node_modules is copied from the host to the image but it looks like in the build everything is done in the images.

```
/usr/server/node_modules/bindings/bindings.js:126
  err = new Error(
```

**Comment by thanaParis** [comment]
[I've opened a PR for the typo.](https://github.com/citrineos/citrineos-core/pull/21) Thanks for bringing that to my attention!

It's possible that there's an issue with the docker cache.
Please try `docker compose build --no-cache`, then `docker compose down` and `docker compose up` as before.

**Comment by majeeel** [comment]
Hello, we had the same problem, also using MacBook Pro M2 with OS Ventura.

We were able to solve it. For whatever reason the deasync package is not installed / built correctly during the build process. We managed to get it up and running when we were ssh'ing into the container and played around a little bit. After a little research adding the following line to the Dockerfile did the trick:

/50_Server/docker/Dockerfile:
120   +  RUN npm rebuild deasync --build-from-source

**Comment by couryrr-afs** [comment]
@majeeel thank you for the information. I had attempted this before with no luck. I tried again this morning. Removing all containers and rebuilding without a cache. I have the RUN command on line 122 of the Dockerfile. It seems to be working now. Docker seems to have been a blocker there for me.
